= Seeing Like a State
Marcus Crane <marcus@utf9k.net>
:page-permalink: /notes/books/seeing-like-a-state
:page-tags: [book, society, government, authority]
:emoji: 📭
:toc: preamble

Compulsory ujamaa villages in Tanzania, collectivisation in Russia, Le Corbusier’s urban planning theory realised in Brasilia, the Great Leap Forward in China, agricultural "modernisation" in the Tropics—the twentieth century has been racked by grand utopian schemes that have inadvertently brought death and disruption to millions. Why do well-intentioned plans for improving the human condition go tragically awry?

== Terms to look up

* [ ] Brasilia
* [ ] Chandigarh

== Ideas

* A state is unable to focus on one single "customer", rather building with all views in mind.

* We have our own personal filters which mean we sometimes only see the positive or negative aspects of a situation.

* Negativity is good in the sense that it is usually actionable and specific.

* A state assumes that each individual can be assigned an address which makes remote working difficult.

== Links

* https://www.goodreads.com/book/show/20186.Seeing_Like_a_State[Seeing Like a State - Goodreads]