#+title: The precursor to Slack
#+date: 2020-09-06
#+source: https://web.archive.org/web/20030713130936/http://shirky.com/writings/group_enemy.html

#+begin_quote
I was talking to Stewart Butterfield about the chat application they're trying here. I said "Hey, how's that going?" He said: "Well, we only had the idea for it two weeks ago. So this is the launch." When you can go from "Hey, I've got an idea" to "Let's launch this in front of a few hundred serious geeks and see how it works," that suggests that there's a platform there that is letting people do some really interesting things really quickly. It's not that you couldn't have built a similar application a couple of years ago, but the cost would have been much higher. And when you lower costs, interesting new kinds of things happen.
#+end_quote

If I didn't know any better, I would say that sounds like a super early mention of a precursor to [[https://slack.com][Slack]].

Slack, as we know it, wasn't launched until 2009 but it was preceeded by another Stewart Butterfield creation: [[https://flickr.com][Flickr]].

I didn't know this until today but it was originally a chat-first site[fn:flickr-chat]. Users would interact with the site solely through chat although this later expanded into having a proper web UI for photo sharing:

#+begin_quote
It wasn’t a photo sharing site, so much as it was a place where
you could go to chat and talk about photos. But none of that activity
was stored in any asynchronous way – there were no Web pages that
hosted the conversations people were having about photos, it was all
just real-time. [fn:flickr-interview]
#+end_quote

Eventually the chat functionality was deprecated in favour of focusing on the photo uploading and management that Flickr became known for.

Funnily enough, Eric Costello's wish came true and Flickr Live did get reborn

#+begin_quote
It’s indefinitely retired. We’re not sure when it will come back,
but we hope to bring it back. It’ll probably be in a different
incarnation than what it originally was. [fn:flickr-interview]
#+end_quote

I do wonder if [[https://web.archive.org/web/20021129050119/http://www.gameneverending.com/][Game Neverending]] will ever see the light of day?

[fn:flickr-chat] https://www.pcworld.com/article/116576/article.html
[fn:flickr-interview] https://web.archive.org/web/20160610133433/http://adaptivepath.org/ideas/e000519/
