baseURL: "https://utf9k.net/"
languageCode: "en-us"
title: "utf9k"
enableRobotsTxt: true
enableGitInfo: false
enableInlineShortcodes: true
buildDrafts: true
buildFuture: true

taxonomies:
  category: categories

params:
  description: "Is this thing even on? I just put some text here to test out link previews. There's real site content though, I swear!"
  title: "utf9k"

menu:
  a:
    - identifier: "blog"
      name: "Blog"
      url: "/blog"
      weight: 1
    - identifier: "projects"
      name: "Projects"
      url: "/projects"
      weight: 2
    - identifier: "questions"
      name: "Questions"
      url: "/questions"
      weight: 3
  b:
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 1
    - identifier: "now"
      name: "Now"
      url: "/now"
      weight: 2
    - identifier: "uses"
      name: "Uses"
      url: "/uses"
      weight: 3
  c:
    - identifier: "books"
      name: "Books"
      url: "/books"
      weight: 1
    - identifier: "games"
      name: "Games"
      url: "/games"
      weight: 2
  d:
    - identifier: "thanks"
      name: "Thanks"
      url: "/thanks"
      weight: 1
    - identifier: "experiments"
      name: "Experiments"
      url: "/experiments"
      weight: 2
    - identifier: "reviews"
      name: "Reviews"
      url: "/reviews"
      weight: 3
    - identifier: "debug"
      name: "Debug"
      url: "/debug"
      weight: 4

headers:
  - for: /**.html
    values:
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block

mediaTypes:
  text/markdown:
    suffixes:
    - md
  text/plain:
    suffixes:
    - txt

outputFormats:
  RSS:
    baseName: "rss"
    mediaType: "application/rss+xml"
  # Support readers who subscribed to the "old" feed at /index.xml
  RSSBackwardsCompat:
    baseName: "index"
    mediaType: "application/rss+xml"
  SearchIndex:
    baseName: "search"
    mediaType: "application/json"
  MarkdownAST:
    baseName: "index"
    isPlainText: true
    mediaType: "text/markdown"
  PlainText:
    baseName: "index"
    isPlainText: true
    mediaType: "text/plain"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "RSSBackwardsCompat"
    - "SearchIndex"
  page:
    - "HTML"
    - "MarkdownAST"
    - "PlainText"

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

services:
  twitter:
    disableInlineCSS: true

security:
  enableInlineShortcodes: true
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^COMMIT_SHA$
      - ^HUGO_
      - ^LANG$
      - ^LANGUAGE$
      - ^LC_ALL$
      - ^NODE_ENV$
      - ^NODE_VERSION$
      - ^PYTHON_VERSION$
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*
