baseurl: "https://utf9k.net/"
languageCode: "en-us"
buildFuture: false
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      footnote: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
