baseURL: "https://utf9k.net/"
languageCode: "en"
title: "utf9k"
enableRobotsTxt: true
enableGitInfo: false
enableInlineShortcodes: true
buildDrafts: true
buildFuture: true

author:
  name: Marcus Crane
  email: marcus@utf9k.net

taxonomies:
  category: categories

params:
  description: "Is this thing even on? I just put some text here to test out link previews. There's real site content though, I swear!"
  title: "utf9k"

menu:
  main:
  - name: "Blog"
    url: "/blog"
    weight: 1
  - name: "Projects"
    url: "/projects"
    weight: 2
  - name: "About"
    url: "/about"
    weight: 3
  - name: "Questions"
    url: "/questions"
    weight: 4
  - name: "RSS"
    url: "/rss.xml"
    weight: 5

headers:
  - for: /**.html
    values:
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block

mediaTypes:
  text/markdown:
    suffixes:
    - md
  text/plain:
    suffixes:
    - txt

outputFormats:
  RSS:
    baseName: "rss"
    mediaType: "application/rss+xml"
  # Support readers who subscribed to the "old" feed at /index.xml
  RSSBackwardsCompat:
    baseName: "index"
    mediaType: "application/rss+xml"
  SearchIndex:
    baseName: "search"
    mediaType: "application/json"
  MarkdownAST:
    baseName: "index"
    isPlainText: true
    mediaType: "text/markdown"
  PlainText:
    baseName: "index"
    isPlainText: true
    mediaType: "text/plain"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "RSSBackwardsCompat"
    - "SearchIndex"
  page:
    - "HTML"
    - "MarkdownAST"
    - "PlainText"

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

services:
  twitter:
    disableInlineCSS: true

security:
  enableInlineShortcodes: true
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^COMMIT_SHA$
      - ^HUGO_
      - ^LANG$
      - ^LANGUAGE$
      - ^LC_ALL$
      - ^NODE_ENV$
      - ^NODE_VERSION$
      - ^PYTHON_VERSION$
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*
