baseurl = "https://utf9k.net/"
languageCode = "en-us"
paginate = 5
buildFuture = true

[params]
  contentTypeName = "blog"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
