# Basic site config stuff
baseURL: https://utf9k.net
title: utf9k
languageCode: en-us

# The weight specified here determines the order that menu
# items are rendered in, rather than the order of the array
menu:
  main:
    - name: Blog
      url: /blog/
      weight: 1
    - name: Reviews
      url: /reviews/
      weight: 2
    - name: Contact
      url: /contact/
      weight: 3

# A bunch of custom parameters that allow the site to be
# slightly more dynamic ie; not having to edit the base
# HTML template to add a new CSS file every time
params:
  custom_css:
    - /css/style.css
    - https://fonts.googleapis.com/css?family=Barlow:300i,600i&display=swap


  static_includes:
    - manifest.json

# BlackFriday is the markdown parser for Hugo. It has a bunch
# of settings that are nice to have but not on by default
blackfriday:
  nofollowLinks: true
  hrefTargetBlank: true

# Render code with classes so we can apply our own CSS style
# that isn't shipped as part of Pygments default set
pygmentsuseclasses: true

# Enable Git information so we can show when a page last updated
enableGitInfo: true

# Enable usage of emoji with shortcodes
enableEmoji: true
