[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.78.2"

[context.production.environment]
HUGO_ENV = "production"

[context.next]
command = "hugo --buildFuture"
base = "next"

