[build]
publish = "public"
command = "yarn run generate-fancy-links && yarn install && yarn run build"

[build.environment]
HUGO_VERSION = "0.83.1"
PYTHON_VERSION = "3.7"

[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy]
command = "yarn run generate-fancy-links && yarn install && yarn run build-next"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.mp4"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://api.mapbox.com; img-src data: blob: *; media-src data: *; script-src 'self' https://api.mapbox.com; connect-src 'self' https://api.mapbox.com https://events.mapbox.com https://*.tiles.mapbox.com ; worker-src 'self' blob: ; child-src 'self' blob: ;"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Permissions-Policy = "interest-cohort=()"

[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]

  checkPaths = ['/']
