[build]
publish = "public"
command = "npm run build:deps && pnpm run test && pnpm run build:metadata && pnpm run build"

[build.environment]
HUGO_VERSION = "0.91.2"
PYTHON_VERSION = "3.8"

[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
	from = "/statistician.js"
	to = "https://plausible.io/js/plausible.js"
	status = 200
	force = true

[[redirects]]
	from = "/api/event"
	to = "https://plausible.io/api/event"
	status = 200
	force = true

[[redirects]]
	from = "/analytics"
	to = "https://plausible.io/utf9k.net"
	status = 301
	force = false

[[redirects]]
  from = "/index.xml"
  to = "/rss.xml"
  status = 301
  force = false

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.mp4"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://api.mapbox.com https://unpkg.com/littlefoot/dist/littlefoot.css; img-src data: blob: *; media-src data: *; script-src 'self' https://api.mapbox.com; connect-src 'self' https://api.mapbox.com https://api.ipinfodb.com https://events.mapbox.com https://*.tiles.mapbox.com https://gunslinger.utf9k.net ; worker-src 'self' blob: ; script-src-elem 'self' 'sha256-+XV7Bs0QypN9E6irhyz17UuREld+WSb4nmZgVxi6kD0=' https://unpkg.com/netlify-cms@%5E2.0.0/dist/netlify-cms.js https://api.mapbox.com https://platform.twitter.com; frame-src 'self' https://www.youtube.com https://platform.twitter.com ; child-src 'self' blob: ;"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Permissions-Policy = "interest-cohort=()"
