version: '3'
services:
  site:
    build: .
    container_name: site
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - redis
    networks:
      - public
      - private
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: on-failure
    networks:
      - public
    depends_on:
      - site
      - redis
  redis:
    container_name: redis
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - private
networks:
  public:
  private:
    internal: true