version: '3'
services:
  site:
    build: .
    container_name: site
    ports:
      - "5000:5000"
    restart: on-failure
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - site