services:
  - type: web
    name: utf9k
    env: static
    buildCommand: yarn build
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
    routes:
      - type: rewrite
        source: /pageview.js
        destination: https://plausible.io/js/plausible.js
  
