#+title: Everything Was Forever, Until It Was No More: The Last Soviet Generation
#+date: 2030-01-01
#+draft: true

I should point out that parts of this book for me are quite hard to follow as it talks about elements of linguistics and other stuff that hasn't clicked yet.

As always, these are notes for myself that I've open sourced but don't use this as source. You should read the book for yourself in case I've misinterpreted anything.

---

The premise of Everything Was Forever is to look into the claim that the collapse of the Soviet Union was both "unexpected yet totally obvious" at the same time according to a lot of accounts. That claim is essentially a paradox and so it tries to answer how that could be.

#+begin_quote
These questions are not about the causes for the collapse but about the conditions that made the collapse possible without making it anticipated
#+end_quote

Perhaps the part I'm most intrigued by is the picture painted by the following quote:

#+begin_quote
In the late 1980s, Françoise Thom argued that, in the context of ubiquitous ideological language, linguistic “symbols cease[d] to work properly,” making the Soviet Union “a world without meaning, without events and without humanity
#+end_quote

As for what that looks like in reality, we'll just have to carry on and see.

* The role of the "master" and what happens if they're gone



* How can you carry out ceremonies without engaging?
