---
title: "Day Xero"
date: 2018-02-15
---
= Day Xero
Marcus Crane <marcus@utf9k.net>
:page-date: 2018-02-15
:page-permalink: /blog/day-xero
:page-tags: [anxiety, work]

Technically it's Day 1 of my new job, a Graduate Site Reliability Engineer at https://www.xero.com/nz/[Xero] but it hasn't officially started since I'm still on my way to the airport.

I told myself that when I finally got my first full time development position, I'd write a big post mortem about how long it took, how many times I was rejected and all that but since I haven't (yet), this is my offering to the Content Overlords.

I don't even know if I actually slept last night because it felt like most of it was like "Oh no, what have I actually learnt over the last year" and other rude things from that pesky doubtful voice we all have.

Excuse me, you silly voice, I'll have you know that I've used and/or fiddled with ahem

link:https://docker.com/[doc]hilink:http://flask.pocoo.org/[ask]ydd4hlink:https://www.python.org/[py]link:https://www.djangoproject.com/[dja]22hflink:https://nodejs.org/en/[nod]j2velink:https://www.npmjs.com/[n]a43link:https://reactjs.org/[rea]flink:https://webpack.js.org/[we]texlink:https://babeljs.io/[abe]gdd0rglink:https://neovim.io/[neov]1fuhlink:https://github.com/[ith]ulink:https://github.com/lepture/mistune[ist]fhlink:https://www.archlinux.org/[rc]8gzvflink:https://www.gnu.org/software/stow/[tow]filink:https://www.mediawiki.org/wiki/MediaWiki[med]uwhlink:https://www.mediawiki.org/wiki/Extension:Tabber[tab]f2link:https://github.com/marcus-crane/dotfiles[do]fqlink:https://github.com/tmux/tmux[tmu]dlink:https://www.neomutt.org/[mu]

and let me tell you, MediaWiki is something... special alright but it's solid!

I'd be silly of course to think that somehow knowing a bunch of frameworks and languages will somehow mean I'm set for life because that's nonsense talk. It's all about knowing picking the right tool for the right job, y'know?

One of the things I'd like to do more this year is reading more about actual software stories. I started reading https://en.wikipedia.org/wiki/Dreaming_in_Code[Dreaming in Code] earlier this year which seems to be a "what not to do" manua. The author, Scott Rosenberg often veers so far into tangents that half the book feels more like a history lesson than development but that's good! Software won't save you, or the planet, on its own. You gotta focus on the people behind it and getting them working together as a proper team.

This post isn't actually about anything as you can tell. It's the https://en.wikipedia.org/wiki/Seinfeld[Seinfeld] of posts. Well, that's not true since Seinfeld isn't actually about nothing, it's just a show without drama. It's supposed to just be regular life because your average person doesn't live out https://en.wikipedia.org/wiki/Sex_and_the_City[Sex in the City] on a daily basis. I've never actually seen that show though, it's just used as a punchline a lot.

I'm sure if I look back at today, I'll wonder what I was even worried about. If you think about friends or coworkers, do you even really remember meeting them? It's like as soon as you properly know someone, you just kinda forget any awkward moments before your first interaction. I suppose it's like that with jobs. You just kinda turn up one day and, assuming you try your best, you just kinda slot in nicely as if you'd been there the whole time.

Anyway, I better deploy this thing before my taxi gets here. It's still kinda crazy to me that I can just give away the https://github.com/marcus-crane/site/blob/95ae742bbf33662f4dd4cf284e463d0f9320c8d1/site/posts/blog/2018/2018-02-12-day-xero.md[actual post file] you're reading with a few entries into a terminal. Yes, I had to manually make that link because this post even in the repo yet! That's like some kinda preemptive sharing, whoaaa mannnnn.

As someone who learnt piece by piece, pouring a bunch of hours into Right Click -> View Page Source, it's nice to give my own stuff back. I can't remember who said it or when but someone once said something along the lines of "I don't write code, I merely borrow it." Their point wasn't that they spend all day on Stack Overflow but rather that none of their ideas are truly original. Nothing is original because it's all inspired by things that came before.

Ok, ok, my time is actually almost up and while I'm a bit freaked out that I'll be diving into my first full time software job after years of being a hobbyist, there's one thing that I try to remind myself. I might not truly know what I'm doing but neither does anyone else.

As someone else once told me:

> Adults are just kids who got older

*EDIT: This post was rushed and not planned out at all but I'll be posting it as is for historical reasons*
