---
title: "What is the future of emergency services?"
date: 2019-03-20
---
= What is the future of emergency services?
Marcus Crane <marcus@utf9k.net>
:page-date: 2019-03-20
:page-permalink: /blog/future-of-emergency-services
:page-tags: [people, future]

Yesterday, I had an onset of severe abdominal pains. I didn't want to overreact so I called https://www.health.govt.nz/your-health/services-and-support/health-care-services/healthline[Healthline] who recommended I see either my GP, or https://en.wikipedia.org/wiki/Emergency_department[A&E] within the next 6 hours.

Shortly after I hung up, I had a pain spike bad enough to make me burst into tears. I wasn't getting anywhere clutching my stomach on the floor so I called an ambulance.

An operator took my information, said that someone would be on their way and then hung up. I waited... and waited... Just over an hour passed before I gave up and called an Uber. One just happened to be 2 minutes away, with the entire trip only taking about 10 minutes from start to finish.

Part of me worried they had turned up only to find me not there so I called back and asked to have the request cancelled. They did so and I asked what the state of the callout was only to find that nothing was ever dispatched due to a high callout rate in my area. Presumably based on my age and the symptoms, they figured I was at low risk?

It didn't leave me with a good feeling or sense of security but it did get me wondering about two things: Statistics and the future of emergency services.

Most of this article would likely have been joking about how there will probably be "Uber for Ambulances" as I often have.

+++
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">new startup idea: uber for ambulances. cheaper rates than a normal ambulance unless rugby is on then it&#39;s 6x surge prices or you&#39;re fucked</p>&mdash; Marcus (@sentreh) <a href="https://twitter.com/sentreh/status/744467417909235712?ref_src=twsrc%5Etfw">June 19, 2016</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
+++

There have been https://www.nytimes.com/2018/10/01/upshot/uber-lyft-and-the-urgency-of-saving-money-on-ambulances.html[a] https://www.buzzfeednews.com/article/carolineodonovan/taking-uber-lyft-emergency-room-legal-liabilities[few] writeups about how patients are using ridesharing services in place of ambulances and I think I understand why.

http://www2.ku.edu/~kuwpaper/2017Papers/201708.pdf[This non-peer reviewed paper] in particular, from the University of Kansas, noted an 8% decline in ambulance callouts following the launch of Uber in each respective city measured in the study.

Now having said all this, there was actually an announcement this time last year for https://www.uber.com/newsroom/uber-health/[Uber Health] in the US. The service is more for booking health-related rides on behalf of patients, as opposed to straight up replacing ambulances but give it enough time and I could see that extra capacity being leveraged to fill in the gaps.

My second question, and one that I'm not really qualified to answer, is to do with the actual callout rates.

The https://en.wikipedia.org/wiki/St_John_New_Zealand[St John] Organisation are the primary dispatcher of ambulances in New Zealand, providing emergency services to https://www.stjohn.org.nz/What-we-do/St-John-Ambulance-Services/[nearly 90% of New Zealanders] according to their own website.

They have a handy https://www.stjohn.org.nz/News--Info/Our-Performance/Response-Times/[section on response times] which links to the https://www.health.govt.nz/new-zealand-health-system/key-health-sector-organisations-and-people/naso-national-ambulance-sector-office/emergency-ambulance-services-eas/performance-quality-and-safety/emergency-ambulance-service-national-performance-reports[Ministry of Health's Emergency Ambulance Service national performance reports]. Look a bit closer and you'll see "For information about St John’s performance visit the performance section of their web site." which just leads us back to where we started!

Thankfully, their annual reports contain some of the information we're after. Let's take the https://www.stjohn.org.nz/globalassets/documents/publications/annual-report/stj-annual-report_2018_lq.pdf[2018 Annual report] as an example.

If we jump all the way to Page 50, we can see a breakdown of numbers with 533,669 ambulance emergency calls made. Another line item mentions 480,411 patients treated or transported by ambulance officers. If we were to very roughly assume that 1 call correlated with 1 patient, that would leave 53,258 calls that are never responded to.

Obviously that's not the whole picture. One call could be for a car crash with multiple injuries while the already deceased may not be counted as "Patients treated or transported". Similarly, it doesn't take into account prank calls, duplicate calls and no-show patients who can't cancel callouts.

Either way, I think it still does point out that there's likely a chunk of callouts that never get responded to as a result of unstaffing combined with ever increasing callout numbers. It's pretty dystopian having something like the "Gig Economy" acting as a replacement for essential services but I suppose I'll take what I can get.

Besides, I never liked the attention that came with flashing lights and sirens anyway.
