---
title: "Night of the Living Build Failures"
date: 2019-11-02
draft: true
---
= Night of the Living Build Failures
Marcus Crane <marcus@utf9k.net>
:page-date: 2019-11-02
:page-draft: true
:page-permalink: /blog/halloween-build-failures
:page-tags: [mystery, investigation, travis, node]
:toc: preamble

Personally I've never been one for contributing heavily to open source projects. While I'll often distribute the source of anything I don't throw away, I've never found myself part of the open source community in any meaningful sense.

Recently I came across https://worldbrain.io/[WorldBrain's Memex], an open source project for knowledge storage. It's a little bit of everything I like about sites like https://getpocket.com[Pocket], https://pinboard.in[Pinboard] and others. It's also the first project that I've been interested in contributing to, since I'd like the concept to be fully fleshed out one day.

Anyway, this post isn't necessarily about Memex but some build failures that the project incurred recently, due to the ever moving nature of the https://nodejs.org[Node] ecosystem.

It ended up being a bit of a detective story and so perhaps it'll come in handy on how you might go about investigating these sorts of things? With that background laid out, let's jump to the beginning.

== The failing build(s)

While this definitely isn't the first build failure I'd consider interesting, it is the first one I've dug into that's out in the open. Thankfully this means you're able to follow along a recreation of the exact steps I took, and see some concrete examples of what went wrong.

I had noticed a few builds failed, but the first indication that they were off was as part of https://github.com/WorldBrain/Memex/pull/894[this pull request] which changed some copyright notices. With no code changing, you wouldn't expect the CI system to fail like that. That's assuming that the primary branch has a passing test suite mind you.

By clicking on the failed build (the red x next to the commit) and clicking "Details", we can go straight to [Travis CI](https://travis-ci.org) and dig a little deeper.

Scrolling past a whole bunch of output, right to the bottom, we see the following error:

[source, bash]
----
The command "yarn install --frozen-lockfile" failed and exited with 1 during .
----

That's... not very helpful.

I could actually spoil the story right now, as the answer is actually a few lines up. If you're like me though, you'd have no context on what half of these lines are, so calling them out won't mean much.

Let's scroll up a little further to Lines 767 to 777

[source, bash]
----
In file included from /home/travis/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../../../../nan/nan.h:54,
                 from ../ext/channel.cc:23:
/home/travis/.cache/node-gyp/12.13.0/include/node/v8.h:2616:37: note: candidate: v8::Maybe<bool> v8::Value::Equals(v8::Local<v8::Context>, v8::Local<v8::Value>) const
   V8_WARN_UNUSED_RESULT Maybe<bool> Equals(Local<Context> context,
                                     ^
/home/travis/.cache/node-gyp/12.13.0/include/node/v8.h:2616:37: note:   candidate expects 2 arguments, 1 provided
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-cast-function-type’ [-Werror]
cc1plus: all warnings being treated as errors
----
