#+title: Now

* Moving

At the moment, I'm in the process of getting ready to (at some point soon) move into a different place

It's all a bit up in the air at the moment given how shared tenancies work and all that

You don't want to find someone too early because then you've got to rush around but you also gotta time it so that you aren't too late to finding a new place or else you might not given them enough notice for the other person to move out

The entire idea is dumb if you ask me but it's just how things work annoyingly

* Emacs

I'm still making solid use of org-mode for all of my GTD bits and pieces

While I had set up ~org-habits~, I didn't make much use of it

Personally, I think going into org-mode to update habits is almost too much friction compared to being able to resolve them on mobile

Well, I guess I could make it work but I somewhat wish there was a dedicated org habit tracking app for mobile devices

Anyway, I've decided I'm going to give [[https://everyday.app][Everyday]] a try for a little bit

Maybe I'll be pleasantly surprised or... maybe I'll convince myself to double down on pure text once more

* Reading

Originally, I set a goal to read 12 books in 12 months

I'm still on track to do that and if anything, I'm well ahead of schedule having read about 9 or so

but!

As [[https://en.wikipedia.org/wiki/Goodhart%27s_law][Goodhart's Law]] dictates, my target has turned into a measure

Specifically, I've mostly been reading shorter books which is fine but not really in the spirit of learning. It's more like the spirit of [[https://www.giantbomb.com/min-maxing/3015-128/][min-maxing]]

In order to fix that, I've decided to update my goal to be reading for ~30 minutes a day

I think I actually put 10 minutes initially (in my habit tracker, see above) but that's just a starting point

That brings me to my next point which is: what am I actually reading?

Currently I've got a few books in progress

- [[https://jamesclear.com/atomic-habits][Atomic Habits]]

  Generally, I'm not one to read "self-help" books which this might seem like at first

  I would compare it more to a GTD for habit building in a sense

  Basically, it goes through the psychology of building habits among other things

  I'm enjoying it more than I expected! Not bad for a random HN recommendation

- [[https://www.penguinrandomhouse.com/books/194417/the-master-switch-by-tim-wu/][The Master Switch]]

  I've owned a physical copy of this book for years now but I'm only getting around to it now

  It basically reviews various industries (radio, film, tv) and how they transitioned from being open to closed ecosystems over time

  I'm about halfway but eventually the idea is to see how the past will inform the future in regards to the internet

  Arguably, we've already seen a closing of portions of the internet with Facebook, Google Amp and other walled gardens
