#+title: Uses

See [[https://uses.tech/][here]] for context

* Development tools
** Editor

[[https://github.com/hlissner/doom-emacs][Doom Emacs]] is my current [[https://www.gnu.org/software/emacs/][Emacs]] distribution of choice.

I use ~evil-mode~ which means Emacs is controlled with ~vim~ keybindings.

Whenever I don't feel like using Emacs, or don't have it installed, I usually reach for [[https://www.sublimetext.com][Sublime Text]], [[https://neovim.io][neovim]] or even [[https://www.nano-editor.org/][nano]]

I have no issue with [[https://code.visualstudio.com][VS Code]] and it's a great tool but there's generally nothing I can't already do in a different editor so 🤷‍♀️

* Hardware

** Home
*** Desktop
A decently powerful custom built desktop running [[https://pop.system76.com/][Pop!_OS]]. It's a really nice Linux distribution, based on Ubuntu, and I highly recommend giving it a try if you're looking for something new.

*** Laptop
I generally use a [[https://support.apple.com/kb/sp715?locale=en_NZ][MacBook Pro 13-inch (2015)]] for any personal projects and general browsing.
*** Phone

I swear I have ADHD when it comes to phones.

Currently, I'm using a [[https://www.samsung.com/nz/smartphones/galaxy-s20/buy/][Samsung Galaxy S20]] running [[https://www.android.com/android-10/][Android 10]] and [[https://play.google.com/store/apps/details?id=bitpit.launcher&hl=en][Niagara Launcher]]

It's actually pretty nice considering Samsung UX can often be a little hit or miss.

** Work
*** Laptop

Currently I'm using a [[https://support.apple.com/kb/SP795?locale=en_NZ][MacBook Pro 13-inch (2019)]] as my daily driver for work.

It's a placeholder while I wait for my intended laptop to arrive from overseas. I think it's a 2020 Macbook Pro but no idea what kind of configuration.

*** Phone

For my work phone, I'm using an [[https://www.apple.com/nz/iphone-se/][iPhone SE (2020)]]

It's under its own apple account as is the laptop above to save my work tabs mixing up with my home tabs

* Software

** Shell

Often I switch around a bit but I'm currently running stock [[https://en.wikipedia.org/wiki/Z_shell][zsh]]

Stock in the sense that I'm not running Oh My Zsh! but rather just a small [[https://github.com/marcus-crane/dotfiles/blob/master/zsh/zshrc.org][handwritten configuration file]].

I'm not running anything fancy as far as terminals: stock macOS terminal and whatever ships with Pop!_OS by default.
