---
title: "Repo Birthdays"
date: 2017
---
= Repo Birthdays
Marcus Crane <marcus@utf9k.net>
:page-date: 2017-12-03
:page-permalink: /projects/repo-birthdays
:page-tags: [chrome, extension, javascript]

I'd often visit a repository and wonder just how old it is. Stars might indicate popularity but I imagine most of the time there's an initial burst of activity that slowly dies off as https://producthunt.com[product hunters] and https://news.ycombinator.com[hacker newsers] fade into the either.

I was also looking for an excuse to make a browser extension and Repo Birthdays was the result. It's pretty straight forward in that it just checks your URL to see if you're on a Github page two levels deep ie `github.com/blah/bleh`.

Instantly, you might realise that a marketing page such as `github.com/staff/about` would trigger this and you're not wrong. It doesn't matter much though since it fails pretty graceful I think.

I haven't looked at this project since I initially released it but perhaps I'll go back and clean it up. Until then, it still operates perfectly fine and I get use out of it every time I visit Github.

You can download it from the Chrome Store https://chrome.google.com/webstore/detail/repo-birthdays/pmfhcjhcddnompkialjfidnbiibbccie[here] or view the source on Github https://github.com/marcus-crane/repo-birthdays[here].
