#+title: Seeing Like A State: How Certain Schemes To Improve The Human Condition Have Failed
#+setupfile: ./hugo_setup.org
#+hugo_slug: seeing_like_a_state
#+roam_tag: books

How did the state gradually get a handle on its subjects and their environment? Suddenly, processes as disparate as the creation of permanent last names, the standardization of weights and measures, the establishment of cadastral surveys and population registers, the invention of freehold tenure, the standardization of language and legal discourse, the design of cities, and the organization of transportation seemed comprehensible as attempts at legibility and simplification.

would enable much of the reality they depicted to be remade. Thus

Thus a state cadastral map created to designate taxable property-holders does not merely describe a system of land tenure; it creates such a system through its ability to give its categories the force of law.

any production process depends on a host of informal practices and improvisations that could never be codified. By merely following the rules meticulously, the workforce can virtually halt production. In the same fashion, the simplified rules animating plans for, say, a city, a village, or a collective farm were inadequate as a set of instructions for creating a functioning social order.

Tennessee Valley Authority, the United States' highmodernist experiment and the granddaddy of all regional development projects.

The term metis, which descends from classical Greek and denotes the knowledge that can come only from practical experience,

Enlightenment's Wake,

In state "fiscal forestry," however, the actual tree with its vast number of possible uses was replaced by an abstract tree representing a volume of lumber or firewood.

The vocabulary used to organize nature typically betrays the overriding interests of its human users. In fact, utilitarian discourse replaces the term "nature" with the term "natural resources," focusing on those aspects of nature that can be appropriated for human use.

plants that are valued become "crops," the species that compete with them are stigmatized as "weeds," and the insects that ingest them are stigmatized as "pests." Thus, trees that are valued become "timber," while species that compete with them become "trash" trees or "underbrush." The same logic applies to fauna. Highly valued animals become "game" or "livestock," while those animals that compete with or prey upon them become "predators" or "varmints."

cameral science,

The monocropped forest was a disaster for peasants who were now deprived of all the grazing, food, raw materials, and medicines that the earlier forest ecology had afforded.

An exceptionally complex process involving soil building, nutrient uptake, and symbiotic relations among fungi, insects, mammals, and flora-which were, and still are, not entirely understood-was apparently disrupted, with serious consequences. Most of these consequences can be traced to the radical simplicity of the scientific forest.

they invented the science of what they called "forest hygiene."

In place of hollow trees that had been home to woodpeckers, owls, and other tree-nesting birds, the foresters provided specially designed boxes. Ant colonies were artificially raised and implanted in the forest, their nests tended by local schoolchildren. Several species of spiders, which had disappeared from the monocropped forest, were reintroduced.26 What is striking about these endeavors is that they are attempts to work around an impoverished habitat still planted with a single species of conifers for production pur- poses.27 In this case, "restoration forestry" attempted with mixed results to create a virtual ecology, while denying its chief sustaining condition: diversity.

while a merchant who stakes everything on a single ship design and size runs a higher risk of losing everything, forest biodiversity acts like an insurance policy.

Society must be remade before it can be the object of quantification. Categories of people and things must be defined, measures must be interchangeable; land and commodities must be conceived as represented by an equivalent in money. There is much of what Weber called rationalization in this, and also a good deal of centralization. -Theodore M. Porter, "Objectivity as Standardization"

State agents have no interest-nor should they-in describ ing an entire social reality, any more than the scientific forester has an interest in describing the ecology of a forest in detail. Their abstractions and simplifications are disciplined by a small number of objectives, and until the nineteenth century the most prominent of these were typically taxation, political control, and conscription. They needed only the techniques and understanding that were adequate to these tasks.

Directly apprehended by the state, so many maps would represent a hopelessly bewildering welter of local standards. They definitely would not lend themselves to aggregation into a single statistical series that would allow state officials to make meaningful comparisons.
