#+title: Showstopper!: The Breakneck Race to Create Windows NT and the Next Generation at Microsoft
#+setupfile: ./hugo_setup.org
#+hugo_slug: showstopper_the_breakneck_race_to_create_windows_nt_and_the_next_generation_at_microsoft
#+roam_tag: book

comments suggest the motivations and reasoning behind the code. Well-written

Cutler was fanatical about supplying reams of comments with his code. These “coding comments,” as programmers call them, are buried inside a program, visible to those who wish to learn more about the intent of the original code writer. It is frustrating but useful to read these comments. Code often persists long after the original code writer leaves the scene; comments suggest the motivations and reasoning behind the code. Well-written comments help those who wish to modify or improve a program. Cutler’s comments were beautiful yet overdone. Practically every line of his code spawned a comment. Wood’s objection partly reflected the reality that he wrote much more code than Cutler and had less time for writing comments. “The problem [with commenting] is that the code evolves,” Wood said. “I’m working on five things, and the code is changing every day,” requiring parallel changes in the comments too. Cutler, of course, had a simple solution to Wood’s problem: As the code changed, change the comments. Wood’s reluctance to document his work made Cutler uptight.

Redmond, Wash.—Four programmers died in a freak accident today when David N. Cutler threw his dick on a second-floor conference table. The dick crashed through the floor and into the lab below, killing the programmers and damaging three computers. Cutler’s dick sustained only minor injuries….

Redmond, Wash.—Rescue workers found the first survivor of the tsunami in the ruins of Microsoft’s corporate campus. David N. Cutler was found clinging to a water fountain. He reported having a pissing match with another Microsoft employee right before the tsunami. Cutler’s only injury appeared to be mild dehydration.

Maritz still noticed that there “was a two-inch pipe with piss going back and forth between the two teams.”

Cutler displayed all the hallmarks of a great Hollywood director. He imposed his tastes and vision on a cast of stars and a crew of talented technicians. He sustained the integrity of his vision by refusing to pander to the marketplace while skillfully gaining the financial resources required for his immense undertaking. Like an Orson Welles, he relied on his skills as an actor and technician as well as a director, making his involvement in his creation more intimate and immediate.

“With his power level, Dave could totally shit on you,” Haluptzok said. “But he doesn’t. He’s a real guy. He makes me feel important. I go to talk with him on important decisions on NT and he gives me full attention. He talks with you like you’re someone worth reckoning with.”

“Driving away Cutler was one of the dumbest fucking things Digital ever did,” one person said. “But we can’t say we screwed up because some of the idiots responsible for that are still here.”

No amount of rhetoric could equal the example of Cutler’s actions. “If I’m in the Build Lab, that tells [the code writer]: I better not check in shit.”

participants expected a copy of NT in their greeting packet (those programmers who couldn’t attend the conference could still buy a copy of NT on a single compact disc for $69).

The veterans would spend so much time tutoring the novices that they would lose track of their work. And by the time the new hires learned enough really to help, the group would have missed the deadline anyway.

“Always do the job right, get it reliable and then worry about performance”

the edifice of Bigness,

Cutler sustained a mythic realm for both himself and his followers, in which the ambiguities of life were transformed into black and white, good and evil.

As player-coach, he promoted the goals of NT and moved the team closer to the finish line.

Too much involvement on the part of a chief executive holds its perils.

the complexity of the system is such that each single piece holds little meaning outside the whole.

it was a god that failed.
