#+title: The Inner Game of Tennis
#+setupfile: ./hugo_setup.org
#+hugo_slug: the_inner_game_of_tennis
#+roam_tag: book to_be_processed

It is the thesis of this book that neither mastery nor satisfaction can be found in the playing of any game without giving some attention to the relatively neglected skills of the inner game

The player of the inner game comes to value the art of relaxed concentration above all other skills

The most common complaint of sportsmen ringing down the corridors of the ages is, “It’s not that I don’t know what to do, it’s that I don’t do what I know!”

I was beginning to learn what all good pros and students of tennis must learn: that images are better than words, showing better than telling, too much instruction worse than none, and that trying often produces negative results.

Great music and art are said to arise from the quiet depths of the unconscious, and true expressions of love are said to come from a source which lies beneath words and thoughts.

WE HAVE ARRIVED AT A KEY POINT: IT IS THE CONSTANT “THINKING” activity of Self 1, the ego-mind, which causes interference with the natural capabilities of Self 2

We simply know the action will come, and when it does, we don’t feel like taking credit; rather, we feel fortunate, “graced.” As Suzuki says, we become “childlike.

Letting go of the judging process is a basic key to the Inner Game

What I mean by judgment is the act of assigning a negative or positive value to an event

If I do, I am likely to get as uptight in the process of correcting him as he is likely to be in correcting himself. Judgment results in tightness, and tightness interferes with the fluidity required for accurate and quick movement

Usually the first thing that needs to be done is to deal with the negative concepts inhibiting the innate developmental process. Both the pro and the player stimulate this process as they begin to see and to accept the strokes as they are at that moment

Here was a business executive who controlled large commercial enterprises of great complexity asking me for help as if he had no control over his own right arm

No matter what a person’s complaint when he has a lesson with me, I have found that the most beneficial first step is to encourage him to see and feel what he is doing—that is, to increase his awareness of what actually is

So at once the player may ask where his racket should be when the ball is bouncing. But I decline to say, asking him only to observe where his racket is at that moment

Uncomfortable without a standard for right and wrong, the judgmental mind makes up standards of its own. Meanwhile, attention is taken off what is and placed on the process of trying to do things right

It was another person who had netted the first ball, and Clare had hit only two balls into the net. Her judgmental mind had distorted her perception of what had actually happened

They were trying to live up to an expectation, a standard of right and wrong, which they felt had been set before them

To see your strokes as they are, there is no need to attribute goodness or badness to them. The same goes for the results of your strokes. You can notice exactly how far out a ball lands without labeling it a “bad” event

Said another way, the less fear and doubt are embedded in the instructional process, the easier it will be to take the natural steps of learning

the person attempts to describe that stroke in language. But words can only represent actions, ideas and experiences. Language is not the action, and at best can only hint at the subtlety and complexity contained in the stroke

it must be acknowledged that remembering the instruction is not the same as remembering the stroke itself

In a society that has become so oriented toward language as a way of representing truth, it is very possible to lose touch with your ability to feel and with it your ability to “remember” the shots themselves

I believe the best use of technical knowledge is to communicate a hint toward a desired destination

Even though what they were told might be “correct,” if they have little experiential understanding of grips or why you change them, it is unlikely that they will really discover the best grips for their game.

gospels change and they are changed by people who had the courage to experiment outside the boundaries of the existing doctrine and trust in their own learning process

This first step of knowing what results you want is critical to maintaining control of the learning process where it belongs—with you

By the word “learning” I do not mean the collection of information, but the realization of something which actually changes one’s behavior—either external behavior, such as a tennis stroke, or internal behavior, such as a pattern of thought

there is no need to fight old habits. Start new ones.

Fighting the mind does not work. What works best is learning to focus it

How to stay concentrated in the here and now between points? My own device, and one that has been effective for many of my students,is to focus attention on breathing

Anxiety is fear about what may happen in the future, and it occurs only when the mind is imagining what the future may bring. But when your attention is on the here and now, the actions which need to be done in the present have their best chance of being successfully accomplished, and as a result the future will become the best possible present

Most of our suffering takes place when we allow our minds to imagine the future or mull over the past. Nonetheless, few people are ever satisfied with what is before them at the moment.

We live in an achievement-oriented society where people tend to be measured by their competence in various endeavors

Do we really think the value of a human being is measurable? It doesn’t really make sense to measure ourselves in comparison with other immeasurable beings

Those who see competition as a form of legalized hostility tend to favor such noncompetitive forms of recreation as surfing, Frisbee or jogging

Winning is overcoming obstacles to reach a goal, but the value in winning is only as great as the value of the goal reached

I arrived at the startling conclusion that true competition is identical with true cooperation. Each player tries his hardest to defeat the other, but in this use of competition it isn’t the other person we are defeating; it is simply a matter of overcoming the obstacles he presents

A very wise person once told me, “When it comes to overcoming obstacles, there are three kinds of people. The first kind sees most obstacles as insurmountable and walks away. The second kind sees an obstacle and says, I can overcome it, and starts to dig under, climb over, or blast through it. The third type of person, before deciding to overcome the obstacle, tries to find a viewpoint where what is on the other side of the obstacle can be seen. Then, only if the reward is worth the effort, does he attempt to overcome the obstacle.”

The need to trust oneself and grow in understanding of our true selves will never diminish

slowly I have found that the demands I’m trying to fulfill when I’m stressing myself are not really my own, but ones I have “picked up” or “bought into” for perhaps no better reason than I heard them early in life, or because they seemed to be so generally accepted.

Focus means not dwelling on the past, either on mistakes or glories; it means not being so caught up in the future, either its fears or its dreams, that my full attention is taken from the present
