[api]
enabled = true
address = "127.0.0.1:8686"

[sources.nginx_access_logs]
  type = "file"
  include = ["/var/log/nginx/access.log"]
  start_at_beginning = false
  ignore_older = 86400

[transforms.nginx_access_logs_json]
  type = "json_parser"
  inputs = ["nginx_access_logs"]

[sinks.elasticsearch]
  type = "elasticsearch"
  inputs = ["nginx_access_logs_json"]
  compression = "none"
  endpoint = "http://[fdaa:0:2d9f:a7b:d6b:0:a:2]:9200"

  auth.strategy = "basic"
  auth.user = "elastic"
  auth.password = "changeme"

  healthcheck.enabled = true
