#+title: Linux
#+date: 2020-08-18
#+tags[]: linux faqs

{{< toc >}}

* Questions
** Why are dot files a thing?

Rob Pike explained his understanding in a now-dead Google+ post back in 2012. The use of ~.~ and ~..~ had appeared in early versions of the Unix file system, as a quick way to navigate around. They would appear when using ~ls~ to view the contents of a directory so a line was added that ignored anything where the first character was a period.

This, of course, meant that any files starting with a ~.~ were also hidden and so began years of bad practices. Rather than think "Where should I store my configuration folder", the easy option became storing a dotfile instead. It may be messy but if no one can see it, is it really so bad?

Rob also points out that configuration could just as easily be stored in ~$HOME/cfg~ or ~$HOME/lib~ as was the case in Plan 9. He doesn't dispute that dotfiles have their uses but emphasizes that the file itself serves the purpose. Prepending a dot does not a configuration file make.

* Troubleshooting
** Why do some of my applications suddenly get muted?

I recently ran into this issue when switching my distro to [[https://manjaro.org][Manjaro]].

I'd find that whenever a different audio source would start playing such as a voice call, notification or even a silent video on the web, my Spotify audio would drop to 0 instantly

In order to fix this, all I needed to do was unload the ~module-role-cork~ module presumably used by ~pulseaudio~

You can toggle via your terminal to test that it works like so:

#+begin_src shell
> pactl unload-module module-role-cork # disabled, try spotify and another audio source
> pactl load-module module-role-cork   # enabled, spotify should be interrupted
#+end_src

While I'm not sure how long ~unload-module~ persists (I'm guessing until the next restart), you can achieve the same effect by commenting out the module in the configuration for ~pulseaudio~ like so:

#+begin_src shell
> grep "cork" /etc/pulse/default.pa -B 3
### Cork music/video streams when a phone stream is active
# Disabling this allows audio streams to run over the top of each other
# Before this, a newer stream (notification, video) would mute Spotify
#load-module module-role-cork
#+end_src

Once that's done, you should be good to go. It seems to work as expected for me anyway.
