name: Generate and publish markdown from org-mode source files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@v2.0
        with:
          version: 27.1
      - name: Install ox-hugo
        run: |
          emacs -Q --batch -L . --eval "(mapc 'package-install '(ox-hugo))"
