name: Synchronize Todoist
on:
  schedule:
   - cron: "*/30 * * * *"
  workflow_dispatch:
    

jobs:
  sync_issues:
    name: Synchronize Github issues with Todoist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: gh gist view ${{ secrets.GIST_ID }} -f sync.json > ./sync.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Sync issues
        id: sync
        uses: cobraz/todoist-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
          query: archived:false sort:updated-desc assignee:<insert your Github username> updated:>2020-06-01 -label:backlog
          sync-file-name: ./sync.json
      
      - name: Deploy
        if: steps.sync.outputs.has-changed == 'true'
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: 77b36845948f1565197e4b914e56a919
          gist_file_name: sync.json
          file_path: ./sync.json
